stools:
  base-url: https://static.run

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/stools?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root
  thymeleaf:
    prefix: classpath:/templates/
    encoding: UTF-8
    cache: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  devtools:
    add-properties: false
vaadin:
  servlet:
    productionMode: true
logging:
  level:
    # root: warn
    web: debug
    run:
      static: debug
  file:
    path: ${user.home}/.STools/logs