stools:
  base-url: http://127.0.0.1:${server.port}
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/stools?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/
    encoding: UTF-8
    cache: false
#  web:
#    resources:
#      chain:
#        strategy:
#          content:
#            paths: /**
#            enabled: true
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
  devtools:
    add-properties: true
logging:
  level:
    # root: warn
    web: debug
    runstatic:
      stools: debug
