spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    active: dev
  pid:
    file: ${stools.work-folder}/application.pid
  sql:
    init:
      data-locations:
        - classpath:sql/*.sql
      mode: NEVER
      continue-on-error: true
  datasource:
    hikari:
      transaction-isolation: TRANSACTION_READ_COMMITTED
server:
  port: 8001
  compression:
    enabled: true
vaadin:
  pnpm-enabled: false
  urlMapping: ${stools.vaadin-base-url}/*
logging:
  file:
    path: ${stools.work-folder}/logs
stools:
  admin:
    enabled: true
    username: root
    password: root
    email: chenmoand@outlook.com
  work-folder: ${user.home}/.STools
  vaadin-base-url: /ui
  web-doc-resources:
    maven: ${stools.web-doc-resources.central}
    central: https://maven.aliyun.com/repository/central
    public: https://maven.aliyun.com/repository/public
    google: https://maven.aliyun.com/repository/google
    gradle-plugin: https://maven.aliyun.com/repository/gradle-plugin
    spring: https://maven.aliyun.com/repository/spring
    grails-core: https://maven.aliyun.com/repository/grails-core
    apache-snapshots: https://maven.aliyun.com/repository/apache-snapshots