spring:
  profiles:
    active: dev
  pid:
    file: ${stools.work-folder}/application.pid
  sql:
    init:
      data-locations:
        - classpath:sql/*.sql
      mode: NEVER
      continue-on-error: true
server:
  port: 8001
  compression:
    enabled: true
springfox:
  documentation:
    swagger-ui:
      base-url: /
      enabled: true
    swagger:
      v2:
        path: /swagger/v2/docs
        enabled: true
vaadin:
  pnpm-enabled: false
logging:
  file:
    path: ${stools.work-folder}/logs
stools:
  work-folder: ${user.home}/.STools
