spring:
  profiles:
    active: dev
  pid:
    file: ${stools.work-folder}/application.pid
  sql:
    init:
      data-locations:
        - classpath:sql/*.sql
      mode: NEVER
      continue-on-error: true
server:
  port: 8001
  compression:
    enabled: true
springfox:
  documentation:
    swagger-ui:
      base-url: /
      enabled: true
    swagger:
      v2:
        path: /swagger/v2/docs
        enabled: true
vaadin:
  pnpm-enabled: false
logging:
  file:
    path: ${stools.work-folder}/logs
stools:
  work-folder: ${user.home}/.STools
  web-doc-resources:
    maven: ${stools.web-doc-resources.central}
    central: https://maven.aliyun.com/repository/central
    public: https://maven.aliyun.com/repository/public
    google: https://maven.aliyun.com/repository/google
    gradle-plugin: https://maven.aliyun.com/repository/gradle-plugin
    spring: https://maven.aliyun.com/repository/spring
    grails-core: https://maven.aliyun.com/repository/grails-core
    apache-snapshots: https://maven.aliyun.com/repository/apache-snapshots